import type { DepartmentConfig, SpecializationConfig } from '@/lib/interview-catalog/types'
import { DEFAULT_HR_TOPICS, DEFAULT_INTERVIEW_TYPES } from '@/lib/interview-catalog/hr-topics'

const B = ['Communication', 'Teamwork', 'Leadership', 'Problem Solving', 'Ownership', 'Handling Pressure']

function spec(
  key: string,
  label: string,
  technicalTopics: string[],
  behavioralTopics: string[] = B,
  technicalQuestionRatio = 75,
): SpecializationConfig {
  return {
    key,
    label,
    interviewTypes: [...DEFAULT_INTERVIEW_TYPES],
    technicalTopics,
    behavioralTopics,
    hrTopics: [...DEFAULT_HR_TOPICS],
    technicalQuestionRatio,
    durationEnabled: true,
    durations: [20, 30, 45, 60],
  }
}

/** Extra computer-field departments beyond SE / IT / DS / AI. */
export const COMPUTER_FIELD_DEPARTMENTS: DepartmentConfig[] = [
  {
    key: 'security_engineering',
    label: 'Cybersecurity',
    specializations: [
      spec('network_security', 'Network Security', [
        'Firewalls',
        'IDS/IPS',
        'VPN',
        'Zero Trust',
        'Network Segmentation',
        'Packet Analysis',
      ]),
      spec('application_security', 'Application Security', [
        'OWASP Top 10',
        'Secure SDLC',
        'Threat Modeling',
        'SAST/DAST',
        'Dependency Scanning',
      ]),
      spec('cloud_security', 'Cloud Security', [
        'IAM',
        'Shared Responsibility',
        'CSPM',
        'Encryption',
        'Logging & Monitoring',
      ]),
      spec('pentesting', 'Penetration Testing', [
        'Reconnaissance',
        'Exploitation',
        'Privilege Escalation',
        'Post-Exploitation',
        'Reporting',
      ]),
      spec('soc_ops', 'SOC / Blue Team', [
        'SIEM',
        'Incident Response',
        'Threat Hunting',
        'Playbooks',
        'EDR',
      ]),
      spec('cryptography', 'Cryptography', [
        'Symmetric/Asymmetric',
        'Hashing',
        'PKI',
        'TLS',
        'Key Management',
      ]),
      spec('identity_access', 'Identity & Access Management', [
        'SSO',
        'OAuth/OIDC',
        'RBAC/ABAC',
        'MFA',
        'Directory Services',
      ]),
      spec('malware_forensics', 'Malware & Forensics', [
        'Static Analysis',
        'Dynamic Analysis',
        'Memory Forensics',
        'Disk Imaging',
        'Chain of Custody',
      ]),
    ],
  },
  {
    key: 'cloud_devops',
    label: 'Cloud & DevOps',
    specializations: [
      spec('aws_platform', 'AWS Platform', [
        'EC2',
        'S3',
        'VPC',
        'IAM',
        'Lambda',
        'RDS',
        'ECS/EKS',
        'CloudWatch',
      ]),
      spec('azure_platform', 'Azure Platform', [
        'Compute',
        'Storage',
        'AAD/Entra',
        'Functions',
        'AKS',
        'Networking',
      ]),
      spec('gcp_platform', 'GCP Platform', [
        'Compute Engine',
        'GKE',
        'Cloud Storage',
        'IAM',
        'Cloud Functions',
        'BigQuery',
      ]),
      spec('kubernetes', 'Kubernetes', [
        'Pods',
        'Deployments',
        'Services',
        'Ingress',
        'ConfigMaps/Secrets',
        'Helm',
        'Observability',
      ]),
      spec('terraform_iac', 'Infrastructure as Code', [
        'Terraform',
        'Modules',
        'State',
        'Ansible',
        'CloudFormation',
        'GitOps',
      ]),
      spec('sre', 'Site Reliability Engineering', [
        'SLIs/SLOs',
        'Error Budgets',
        'On-Call',
        'Incident Management',
        'Capacity Planning',
      ]),
      spec('observability', 'Observability', [
        'Metrics',
        'Logs',
        'Traces',
        'Prometheus',
        'Grafana',
        'OpenTelemetry',
      ]),
      spec('cicd_pipelines', 'CI/CD Pipelines', [
        'Build',
        'Test Automation',
        'Deploy Strategies',
        'Secrets',
        'Artifact Registries',
      ]),
      spec('serverless', 'Serverless', [
        'Functions',
        'Event Sources',
        'Cold Starts',
        'API Gateway',
        'Cost Controls',
      ]),
    ],
  },
  {
    key: 'mobile_engineering',
    label: 'Mobile Development',
    specializations: [
      spec('android', 'Android', [
        'Kotlin',
        'Jetpack',
        'Compose',
        'Lifecycle',
        'Networking',
        'Play Store',
      ]),
      spec('ios', 'iOS', [
        'Swift',
        'SwiftUI',
        'UIKit',
        'Combine',
        'App Store',
        'Memory',
      ]),
      spec('react_native', 'React Native', [
        'Components',
        'Navigation',
        'Native Modules',
        'Performance',
        'Release',
      ]),
      spec('flutter', 'Flutter', [
        'Widgets',
        'Dart',
        'State Management',
        'Platform Channels',
        'Performance',
      ]),
      spec('mobile_architecture', 'Mobile Architecture', [
        'Clean Architecture',
        'Offline Sync',
        'Push Notifications',
        'Deep Linking',
        'Security',
      ]),
    ],
  },
  {
    key: 'quality_assurance',
    label: 'Quality Assurance',
    specializations: [
      spec('manual_qa', 'Manual QA', [
        'Test Cases',
        'Exploratory Testing',
        'Bug Reporting',
        'Regression',
        'UAT',
      ]),
      spec('automation_qa', 'Test Automation', [
        'Selenium',
        'Cypress',
        'Playwright',
        'Page Object',
        'CI Integration',
      ]),
      spec('api_testing', 'API Testing', [
        'REST',
        'Postman',
        'Contract Testing',
        'Auth Flows',
        'Performance Basics',
      ]),
      spec('performance_testing', 'Performance Testing', [
        'Load',
        'Stress',
        'JMeter/k6',
        'Bottlenecks',
        'SLAs',
      ]),
      spec('security_testing', 'Security Testing', [
        'OWASP',
        'Auth Flaws',
        'Injection',
        'XSS',
        'Misconfiguration',
      ]),
    ],
  },
  {
    key: 'database_engineering',
    label: 'Database Engineering',
    specializations: [
      spec('relational_db', 'Relational Databases', [
        'SQL',
        'Normalization',
        'Indexes',
        'Transactions',
        'Query Plans',
      ]),
      spec('nosql', 'NoSQL', [
        'Document Stores',
        'Key-Value',
        'Wide-Column',
        'Consistency Models',
        'Sharding',
      ]),
      spec('data_modeling', 'Data Modeling', [
        'ER Diagrams',
        'Star/Snowflake',
        'OLTP vs OLAP',
        'Schema Evolution',
      ]),
      spec('db_performance', 'Database Performance', [
        'Indexing Strategy',
        'Locking',
        'Partitioning',
        'Caching',
        'Replication',
      ]),
      spec('data_warehousing', 'Data Warehousing', [
        'ETL/ELT',
        'Dimensional Modeling',
        'Snowflake/BigQuery',
        'dbt Basics',
      ]),
    ],
  },
  {
    key: 'game_development',
    label: 'Game Development',
    specializations: [
      spec('unity_dev', 'Unity', [
        'Scenes',
        'GameObjects',
        'C# Scripting',
        'Physics',
        'UI',
        'Optimization',
      ]),
      spec('unreal_dev', 'Unreal Engine', [
        'Blueprints',
        'Actors',
        'C++ Basics',
        'Animation',
        'Networking',
      ]),
      spec('game_systems', 'Game Systems', [
        'Game Loop',
        'ECS',
        'Collision',
        'AI/NPC',
        'Save Systems',
      ]),
      spec('multiplayer', 'Multiplayer', [
        'Client-Server',
        'Latency',
        'Replication',
        'Matchmaking',
        'Anti-Cheat Basics',
      ]),
    ],
  },
  {
    key: 'embedded_iot',
    label: 'Embedded & IoT',
    specializations: [
      spec('embedded_c', 'Embedded C/C++', [
        'Microcontrollers',
        'Interrupts',
        'Peripherals',
        'RTOS Basics',
        'Power Management',
      ]),
      spec('iot_systems', 'IoT Systems', [
        'Sensors',
        'MQTT',
        'Edge Computing',
        'Device Security',
        'OTA Updates',
      ]),
      spec('firmware', 'Firmware', [
        'Bootloaders',
        'Flashing',
        'Debugging',
        'Hardware Interfaces',
        'Reliability',
      ]),
    ],
  },
  {
    key: 'product_tech',
    label: 'Product & Technical PM',
    specializations: [
      spec('technical_pm', 'Technical Product Management', [
        'Roadmaps',
        'PRDs',
        'Metrics',
        'Stakeholder Mgmt',
        'Prioritization',
      ]),
      spec('product_analytics', 'Product Analytics', [
        'Funnel Metrics',
        'A/B Testing',
        'Cohorts',
        'Dashboards',
        'Experiment Design',
      ]),
      spec('platform_pm', 'Platform Product', [
        'APIs',
        'Developer Experience',
        'SLAs',
        'Integrations',
        'Governance',
      ]),
    ],
  },
  {
    key: 'computer_networking',
    label: 'Computer Networking',
    specializations: [
      spec('network_fundamentals', 'Network Fundamentals', [
        'OSI/TCP-IP',
        'Routing',
        'Switching',
        'Subnetting',
        'DNS',
        'DHCP',
      ]),
      spec('network_engineering', 'Network Engineering', [
        'BGP/OSPF',
        'VLANs',
        'Load Balancing',
        'WAN',
        'QoS',
      ]),
      spec('network_automation', 'Network Automation', [
        'Python',
        'Ansible',
        'APIs',
        'Monitoring',
        'Config Management',
      ]),
    ],
  },
]
