import type { DepartmentConfig, SpecializationConfig } from '@/lib/interview-catalog/types'
import { buildComputerScienceDepartmentFromLegacy } from '@/lib/interview-catalog/legacy-cs'
import { DEFAULT_HR_TOPICS, DEFAULT_INTERVIEW_TYPES } from '@/lib/interview-catalog/hr-topics'

const B = ['Communication', 'Teamwork', 'Leadership', 'Problem Solving', 'Stakeholder Management']

function spec(
  key: string,
  label: string,
  technicalTopics: string[],
  behavioralTopics: string[] = B,
  technicalQuestionRatio = 70,
  hrTopics: string[] = [...DEFAULT_HR_TOPICS],
): SpecializationConfig {
  return {
    key,
    label,
    interviewTypes: [...DEFAULT_INTERVIEW_TYPES],
    technicalTopics,
    behavioralTopics,
    hrTopics,
    technicalQuestionRatio,
    durationEnabled: true,
    durations: [20, 30, 45, 60],
  }
}

const OTHER_DEPARTMENTS: DepartmentConfig[] = [
  {
    key: 'software_engineering',
    label: 'Software Engineering',
    specializations: [
      spec('backend', 'Backend Engineering', ['APIs', 'Microservices', 'System Design', 'Databases', 'Caching']),
      spec('frontend', 'Frontend Engineering', ['React', 'TypeScript', 'CSS', 'Performance', 'Accessibility']),
      spec('full_stack', 'Full Stack', ['APIs', 'React', 'Databases', 'Auth', 'Deployment']),
      spec('devops', 'DevOps', ['CI/CD', 'Docker', 'Kubernetes', 'Monitoring', 'Infrastructure as Code']),
      spec('docker_k8s', 'Docker & Kubernetes', [
        'Containers',
        'Images',
        'Pods',
        'Services',
        'Deployments',
        'Helm',
        'Networking',
      ]),
      spec('jenkins', 'Jenkins', ['Pipelines', 'Jobs', 'Agents', 'Plugins', 'CI/CD']),
      spec('github_actions', 'GitHub Actions', ['Workflows', 'Actions', 'Runners', 'Secrets', 'CI/CD']),
      spec('javascript', 'JavaScript', ['Closures', 'Prototypes', 'Async', 'ES6', 'DOM']),
      spec('typescript', 'TypeScript', ['Types', 'Generics', 'Interfaces', 'Utility Types', 'Strict Mode']),
      spec('nodejs', 'Node.js', ['Event Loop', 'Streams', 'Modules', 'Async Patterns', 'Performance']),
      spec('express', 'Express.js', ['Routing', 'Middleware', 'Error Handling', 'Auth', 'REST APIs']),
      spec('mongodb', 'MongoDB', ['CRUD', 'Indexes', 'Aggregation', 'Schema Design', 'Transactions']),
      spec('nextjs', 'Next.js', ['App Router', 'Server Components', 'Caching', 'API Routes', 'SSR']),
      spec('python', 'Python', ['OOP', 'Async', 'Data Structures', 'Testing', 'Packaging']),
      spec('django', 'Django', ['ORM', 'Views', 'Auth', 'REST Framework', 'Migrations']),
      spec('fastapi', 'FastAPI', ['Routing', 'Pydantic', 'Dependency Injection', 'Async', 'OpenAPI']),
      spec('flask', 'Flask', ['Routing', 'Blueprints', 'Jinja', 'Auth', 'Extensions']),
      spec('java', 'Java', ['OOP', 'Collections', 'Concurrency', 'JVM', 'Streams']),
      spec('spring_boot', 'Spring Boot', ['DI', 'Spring MVC', 'JPA', 'Security', 'Actuator']),
      spec('cpp', 'C++', ['Memory', 'STL', 'OOP', 'Concurrency', 'Templates']),
      spec('clang', 'C', ['Pointers', 'Memory', 'Arrays', 'Structs', 'Compilation']),
      spec('csharp', 'C#', ['OOP', 'LINQ', 'Async', 'Generics', 'Memory']),
      spec('dotnet', '.NET', ['ASP.NET', 'EF Core', 'DI', 'Middleware', 'Hosting']),
      spec('golang', 'Go', ['Goroutines', 'Channels', 'Interfaces', 'Packages', 'Testing']),
      spec('rust', 'Rust', ['Ownership', 'Borrowing', 'Traits', 'Error Handling', 'Concurrency']),
      spec('php', 'PHP', ['OOP', 'Composer', 'Sessions', 'Security', 'Performance']),
      spec('laravel', 'Laravel', ['Eloquent', 'Routing', 'Auth', 'Queues', 'Blade']),
      spec('kotlin', 'Kotlin', ['Coroutines', 'Null Safety', 'Collections', 'Android Basics', 'Multiplatform']),
      spec('ruby', 'Ruby', ['OOP', 'Rails Basics', 'Gems', 'Metaprogramming', 'Testing']),
      spec('swift', 'Swift', ['Optionals', 'Protocols', 'Concurrency', 'UIKit/SwiftUI', 'Memory']),
      spec('react', 'React.js', ['Hooks', 'State', 'Effects', 'Performance', 'Testing']),
      spec('angular', 'Angular', ['Components', 'RxJS', 'Dependency Injection', 'Routing', 'Forms']),
      spec('vue', 'Vue', ['Composition API', 'Reactivity', 'Vue Router', 'Pinia', 'SSR']),
      spec('svelte', 'Svelte', ['Reactivity', 'Stores', 'Components', 'Transitions', 'SvelteKit']),
      spec('html_css', 'HTML & CSS', ['Semantics', 'Flexbox', 'Grid', 'Accessibility', 'Responsive']),
      spec('tailwind', 'Tailwind CSS', ['Utility Classes', 'Responsive', 'Custom Theme', 'Layout', 'Dark Mode']),
      spec('nestjs', 'NestJS', ['Modules', 'DI', 'Controllers', 'Guards', 'Pipes']),
      spec('mern', 'MERN Stack', ['React', 'Node.js', 'Express', 'MongoDB', 'Auth']),
      spec('mysql', 'MySQL', ['SQL Queries', 'Indexes', 'Joins', 'Transactions', 'Normalization']),
      spec('postgresql', 'PostgreSQL', ['SQL Queries', 'Indexes', 'Joins', 'Transactions', 'JSON/JSONB']),
      spec('sqlserver', 'SQL Server', ['T-SQL', 'Indexes', 'Stored Procedures', 'Transactions', 'Security']),
      spec('oracle_db', 'Oracle Database', ['SQL', 'PL/SQL', 'Indexes', 'Transactions', 'Performance']),
      spec('sqlite', 'SQLite', ['SQL Queries', 'Schema Design', 'Indexes', 'Transactions', 'Embedded Use']),
      spec('redis', 'Redis', ['Data Structures', 'Caching', 'Pub/Sub', 'Persistence', 'Clustering']),
      spec('firebase', 'Firebase', ['Auth', 'Firestore', 'Realtime DB', 'Cloud Functions', 'Security Rules']),
      spec('dynamodb', 'DynamoDB', ['Keys', 'Indexes', 'Queries', 'Capacity', 'Streams']),
      spec('cassandra', 'Cassandra', ['Data Modeling', 'CQL', 'Partitioning', 'Consistency', 'Clusters']),
      spec('aws', 'AWS', ['EC2', 'S3', 'IAM', 'Lambda', 'Networking']),
      spec('azure', 'Azure', ['Compute', 'Storage', 'Identity', 'Functions', 'Networking']),
      spec('gcp', 'GCP', ['Compute Engine', 'Cloud Storage', 'IAM', 'Cloud Functions', 'Networking']),
      spec('selenium', 'Selenium', ['WebDriver', 'Locators', 'Waits', 'Page Object', 'CI Integration']),
      spec('cypress', 'Cypress', ['Commands', 'Assertions', 'Fixtures', 'Interception', 'CI']),
      spec('playwright', 'Playwright', ['Locators', 'Assertions', 'Tracing', 'Parallel', 'CI']),
      spec('jest', 'Jest', ['Matchers', 'Mocks', 'Async Tests', 'Coverage', 'Snapshots']),
      spec('unity', 'Unity', ['Scenes', 'GameObjects', 'Scripting', 'Physics', 'UI']),
      spec('unreal', 'Unreal Engine', ['Blueprints', 'Actors', 'C++ Basics', 'Physics', 'UI']),
      spec('ethical_hacking', 'Ethical Hacking', [
        'Reconnaissance',
        'Exploitation',
        'Privilege Escalation',
        'Reporting',
        'Tools',
      ]),
      spec('secure_coding', 'Secure Coding', [
        'Input Validation',
        'Auth Flaws',
        'Crypto Basics',
        'Least Privilege',
        'Code Review',
      ]),
      spec('owasp', 'OWASP', [
        'Injection',
        'Broken Auth',
        'XSS',
        'SSRF',
        'Security Misconfiguration',
      ]),
      spec('web_security', 'Web Security', [
        'HTTPS/TLS',
        'CORS',
        'CSRF',
        'Session Security',
        'Headers',
      ]),
      spec('oop', 'Object-Oriented Programming', [
        'Encapsulation',
        'Inheritance',
        'Polymorphism',
        'Abstraction',
        'SOLID',
      ]),
      spec('dbms', 'Database Management Systems', [
        'ER Modeling',
        'Normalization',
        'Transactions',
        'Indexing',
        'Concurrency Control',
      ]),
      spec('operating_systems', 'Operating Systems', [
        'Processes',
        'Threads',
        'Memory Management',
        'Scheduling',
        'File Systems',
      ]),
      spec('computer_networks', 'Computer Networks', [
        'OSI/TCP-IP',
        'Routing',
        'DNS',
        'HTTP',
        'Congestion Control',
      ]),
      spec('software_engineering_fundamentals', 'Software Engineering Fundamentals', [
        'SDLC',
        'Requirements',
        'Design Patterns',
        'Testing',
        'Maintenance',
      ]),
      spec('prompt_engineering', 'Prompt Engineering', [
        'Prompt Design',
        'Few-Shot',
        'Chain of Thought',
        'Evaluation',
        'Safety',
      ]),
      spec('ai_agents', 'AI Agents', [
        'Tool Use',
        'Planning',
        'Memory',
        'Multi-Agent',
        'Evaluation',
      ]),
      spec('rag', 'RAG', [
        'Chunking',
        'Embeddings',
        'Retrieval',
        'Reranking',
        'Grounding',
      ]),
      spec('mobile', 'Mobile Development', ['Mobile UI', 'APIs', 'State', 'Offline', 'Release']),
      spec('qa', 'QA Engineering', ['Test Design', 'Bug Reporting', 'Regression', 'API Testing', 'Coverage']),
      spec('sqa_automation', 'SQA Automation', ['Selenium', 'Cypress', 'CI Pipelines', 'Assertions', 'Flaky Tests']),
      spec('game_dev', 'Game Development', ['Game Loops', 'Physics', 'Rendering', 'Networking', 'Optimization']),
      spec('dsa', 'Data Structures & Algorithms', [
        'Arrays',
        'Strings',
        'Linked Lists',
        'Stacks',
        'Queues',
        'Trees',
        'BST',
        'Heaps',
        'Graphs',
        'Dynamic Programming',
        'Greedy',
        'Backtracking',
      ]),
      spec('system_design_topics', 'System Design Topics', [
        'Scalability',
        'Caching',
        'Load Balancers',
        'Databases',
        'Sharding',
        'Message Queues',
        'Microservices',
        'CAP Theorem',
        'High-Level Design',
        'Low-Level Design',
      ]),
    ],
  },
  {
    key: 'information_technology',
    label: 'Information Technology',
    specializations: [
      spec('it_support', 'IT Support', ['Troubleshooting', 'Networking', 'Active Directory', 'Ticketing']),
      spec('systems_admin', 'Systems Administration', ['Linux', 'Windows Server', 'Virtualization', 'Backups']),
      spec('it_security', 'IT Security', ['Access Control', 'Incident Response', 'SIEM', 'Endpoint Security']),
      spec('ethical_hacking', 'Ethical Hacking', [
        'Reconnaissance',
        'Exploitation',
        'Privilege Escalation',
        'Reporting',
        'Tools',
      ]),
      spec('secure_coding', 'Secure Coding', [
        'Input Validation',
        'Auth Flaws',
        'Crypto Basics',
        'Least Privilege',
        'Code Review',
      ]),
      spec('owasp', 'OWASP', [
        'Injection',
        'Broken Auth',
        'XSS',
        'SSRF',
        'Security Misconfiguration',
      ]),
      spec('web_security', 'Web Security', [
        'HTTPS/TLS',
        'CORS',
        'CSRF',
        'Session Security',
        'Headers',
      ]),
    ],
  },
  {
    key: 'finance',
    label: 'Finance',
    specializations: [
      spec('corporate_finance', 'Corporate Finance', ['Budgeting', 'Forecasting', 'Working Capital', 'Capital Structure']),
      spec('investment_banking', 'Investment Banking', [
        'Valuation',
        'Mergers & Acquisitions',
        'Financial Statements',
        'Capital Markets',
        'DCF',
        'Equity Research',
      ]),
      spec('financial_analysis', 'Financial Analysis', ['Ratio Analysis', 'Variance Analysis', 'Modeling', 'Reporting']),
      spec('risk_management', 'Risk Management', ['Market Risk', 'Credit Risk', 'VaR', 'Stress Testing']),
      spec('taxation', 'Taxation', ['Corporate Tax', 'Tax Planning', 'Compliance', 'International Tax']),
      spec('auditing', 'Auditing', ['Internal Controls', 'Audit Procedures', 'IFRS', 'GAAP']),
      spec('financial_modeling', 'Financial Modeling', ['DCF', 'LBO', 'Three-Statement Models', 'Sensitivity Analysis']),
    ],
  },
  {
    key: 'accounting',
    label: 'Accounting',
    specializations: [
      spec('financial_accounting', 'Financial Accounting', ['Journal Entries', 'Ledgers', 'IFRS', 'GAAP']),
      spec('management_accounting', 'Management Accounting', ['Costing', 'Budgeting', 'Variance Analysis']),
      spec('tax_accounting', 'Tax Accounting', ['Tax Returns', 'Deferred Tax', 'Compliance']),
    ],
  },
  {
    key: 'marketing',
    label: 'Marketing',
    specializations: [
      spec('digital_marketing', 'Digital Marketing', [
        'SEO',
        'Google Ads',
        'Meta Ads',
        'Email Marketing',
        'Analytics',
        'Content Strategy',
      ]),
      spec('seo', 'SEO', ['Keyword Research', 'On-Page SEO', 'Technical SEO', 'Link Building']),
      spec('sem', 'SEM', ['Google Ads', 'Campaign Structure', 'Bidding', 'Quality Score']),
      spec('branding', 'Branding', ['Brand Strategy', 'Positioning', 'Messaging', 'Identity']),
      spec('social_media', 'Social Media Marketing', ['Content Calendar', 'Community Management', 'Paid Social']),
      spec('content_marketing', 'Content Marketing', ['Content Strategy', 'Copywriting', 'Editorial Planning']),
      spec('product_marketing', 'Product Marketing', ['Go-to-Market', 'Positioning', 'Launch Plans', 'Competitive Analysis']),
    ],
  },
  {
    key: 'human_resources',
    label: 'Human Resources',
    specializations: [
      spec('recruitment', 'Recruitment', ['Sourcing', 'Interviewing', 'Employer Branding', 'ATS']),
      spec('employee_relations', 'Employee Relations', ['Conflict Resolution', 'Policy', 'Engagement']),
      spec('payroll', 'Payroll', ['Payroll Processing', 'Benefits', 'Compliance', 'Tax Withholding']),
      spec('performance_management', 'Performance Management', ['OKRs', 'Reviews', 'Feedback', 'PIP']),
      spec('organizational_behavior', 'Organizational Behavior', ['Culture', 'Change Management', 'Motivation']),
    ],
  },
  {
    key: 'business_administration',
    label: 'Business Administration',
    specializations: [
      spec('operations', 'Operations', ['Process Improvement', 'KPIs', 'Supply Chain Basics']),
      spec('strategy', 'Strategy', ['Market Analysis', 'Competitive Strategy', 'Business Models']),
      spec('project_management', 'Project Management', ['Agile', 'Scrum', 'Risk', 'Stakeholders']),
    ],
  },
  {
    key: 'economics',
    label: 'Economics',
    specializations: [
      spec('microeconomics', 'Microeconomics', ['Supply & Demand', 'Elasticity', 'Market Structures']),
      spec('macroeconomics', 'Macroeconomics', ['GDP', 'Inflation', 'Monetary Policy', 'Fiscal Policy']),
      spec('econometrics', 'Econometrics', ['Regression', 'Hypothesis Testing', 'Time Series']),
    ],
  },
  {
    key: 'electrical_engineering',
    label: 'Electrical Engineering',
    specializations: [
      spec('power_systems', 'Power Systems', ['Transformers', 'Grid Stability', 'Protection Systems']),
      spec('electronics', 'Electronics', ['Analog Circuits', 'Digital Logic', 'Semiconductors']),
      spec('embedded_systems', 'Embedded Systems', ['Microcontrollers', 'RTOS', 'Firmware', 'Peripherals']),
      spec('control_systems', 'Control Systems', ['PID', 'State Space', 'Stability', 'Feedback']),
      spec('signal_processing', 'Signal Processing', ['Fourier Analysis', 'Filters', 'DSP', 'Sampling']),
    ],
  },
  {
    key: 'mechanical_engineering',
    label: 'Mechanical Engineering',
    specializations: [
      spec('thermodynamics', 'Thermodynamics', ['Heat Transfer', 'Energy Systems', 'Cycles']),
      spec('fluid_mechanics', 'Fluid Mechanics', ['Bernoulli', 'Turbulence', 'Pumps']),
      spec('machine_design', 'Machine Design', ['Stress Analysis', 'Materials', 'CAD Basics']),
    ],
  },
  {
    key: 'civil_engineering',
    label: 'Civil Engineering',
    specializations: [
      spec('structural', 'Structural Engineering', ['Loads', 'Concrete', 'Steel Design']),
      spec('geotechnical', 'Geotechnical', ['Soil Mechanics', 'Foundations', 'Slope Stability']),
      spec('transportation', 'Transportation', ['Traffic Engineering', 'Highway Design', 'Planning']),
    ],
  },
  {
    key: 'data_science',
    label: 'Data Science',
    specializations: [
      spec('analytics', 'Analytics', ['SQL', 'Dashboards', 'A/B Testing', 'Metrics']),
      spec('machine_learning', 'Machine Learning', ['Supervised Learning', 'Feature Engineering', 'Model Evaluation']),
      spec('data_engineering', 'Data Engineering', ['ETL', 'Pipelines', 'Warehousing', 'Spark']),
    ],
  },
  {
    key: 'artificial_intelligence',
    label: 'Artificial Intelligence',
    specializations: [
      spec('machine_learning', 'Machine Learning', ['Regression', 'Classification', 'Ensembles', 'Validation']),
      spec('deep_learning', 'Deep Learning', ['Neural Networks', 'CNNs', 'RNNs', 'Transformers']),
      spec('nlp', 'NLP', ['Tokenization', 'Embeddings', 'LLMs', 'Text Classification']),
      spec('prompt_engineering', 'Prompt Engineering', [
        'Prompt Design',
        'Few-Shot',
        'Chain of Thought',
        'Evaluation',
        'Safety',
      ]),
      spec('ai_agents', 'AI Agents', [
        'Tool Use',
        'Planning',
        'Memory',
        'Multi-Agent',
        'Evaluation',
      ]),
      spec('rag', 'RAG', [
        'Chunking',
        'Embeddings',
        'Retrieval',
        'Reranking',
        'Grounding',
      ]),
    ],
  },
  {
    key: 'healthcare',
    label: 'Healthcare',
    specializations: [
      spec('clinical', 'Clinical Knowledge', ['Patient Care', 'Diagnosis Basics', 'Medical Ethics']),
      spec('health_admin', 'Healthcare Administration', ['HIPAA', 'Operations', 'Quality Improvement']),
      spec('public_health', 'Public Health', ['Epidemiology', 'Health Policy', 'Prevention']),
    ],
  },
  {
    key: 'law',
    label: 'Law',
    specializations: [
      spec('corporate_law', 'Corporate Law', ['Contracts', 'M&A', 'Compliance', 'Governance']),
      spec('criminal_law', 'Criminal Law', ['Elements of Crime', 'Procedure', 'Evidence']),
      spec('intellectual_property', 'Intellectual Property', ['Patents', 'Trademarks', 'Copyright']),
    ],
  },
  {
    key: 'psychology',
    label: 'Psychology',
    specializations: [
      spec('clinical_psych', 'Clinical Psychology', ['Assessment', 'Therapeutic Approaches', 'Ethics']),
      spec('organizational_psych', 'Organizational Psychology', ['Motivation', 'Teams', 'Leadership']),
      spec('cognitive_psych', 'Cognitive Psychology', ['Memory', 'Attention', 'Decision Making']),
    ],
  },
  {
    key: 'education',
    label: 'Education',
    specializations: [
      spec('pedagogy', 'Pedagogy', ['Lesson Planning', 'Assessment', 'Classroom Management']),
      spec('curriculum', 'Curriculum Design', ['Learning Objectives', 'Standards', 'Differentiation']),
      spec('edtech', 'Educational Technology', ['LMS', 'Digital Tools', 'Accessibility']),
    ],
  },
]

export const INTERVIEW_CATALOG_DEPARTMENTS: DepartmentConfig[] = [
  buildComputerScienceDepartmentFromLegacy(),
  ...OTHER_DEPARTMENTS,
]
