import type { DepartmentConfig, SpecializationConfig } from '@/lib/interview-catalog/types'
import { buildComputerScienceDepartmentFromLegacy } from '@/lib/interview-catalog/legacy-cs'
import { COMPUTER_FIELD_DEPARTMENTS } from '@/lib/interview-catalog/computer-fields-data'
import { DEFAULT_HR_TOPICS, DEFAULT_INTERVIEW_TYPES } from '@/lib/interview-catalog/hr-topics'

const B = ['Communication', 'Teamwork', 'Leadership', 'Problem Solving', 'Stakeholder Management']

function spec(
  key: string,
  label: string,
  technicalTopics: string[],
  behavioralTopics: string[] = B,
  technicalQuestionRatio = 70,
  hrTopics: string[] = [...DEFAULT_HR_TOPICS],
): SpecializationConfig {
  return {
    key,
    label,
    interviewTypes: [...DEFAULT_INTERVIEW_TYPES],
    technicalTopics,
    behavioralTopics,
    hrTopics,
    technicalQuestionRatio,
    durationEnabled: true,
    durations: [20, 30, 45, 60],
  }
}

const OTHER_DEPARTMENTS: DepartmentConfig[] = [
  {
    key: 'software_engineering',
    label: 'Software Engineering',
    specializations: [
      spec('backend', 'Backend Engineering', ['APIs', 'Microservices', 'System Design', 'Databases', 'Caching']),
      spec('frontend', 'Frontend Engineering', ['React', 'TypeScript', 'CSS', 'Performance', 'Accessibility']),
      spec('full_stack', 'Full Stack', ['APIs', 'React', 'Databases', 'Auth', 'Deployment']),
      spec('devops', 'DevOps', ['CI/CD', 'Docker', 'Kubernetes', 'Monitoring', 'Infrastructure as Code']),
      spec('docker_k8s', 'Docker & Kubernetes', [
        'Containers',
        'Images',
        'Pods',
        'Services',
        'Deployments',
        'Helm',
        'Networking',
      ]),
      spec('jenkins', 'Jenkins', ['Pipelines', 'Jobs', 'Agents', 'Plugins', 'CI/CD']),
      spec('github_actions', 'GitHub Actions', ['Workflows', 'Actions', 'Runners', 'Secrets', 'CI/CD']),
      spec('javascript', 'JavaScript', ['Closures', 'Prototypes', 'Async', 'ES6', 'DOM']),
      spec('typescript', 'TypeScript', ['Types', 'Generics', 'Interfaces', 'Utility Types', 'Strict Mode']),
      spec('nodejs', 'Node.js', ['Event Loop', 'Streams', 'Modules', 'Async Patterns', 'Performance']),
      spec('express', 'Express.js', ['Routing', 'Middleware', 'Error Handling', 'Auth', 'REST APIs']),
      spec('mongodb', 'MongoDB', ['CRUD', 'Indexes', 'Aggregation', 'Schema Design', 'Transactions']),
      spec('nextjs', 'Next.js', ['App Router', 'Server Components', 'Caching', 'API Routes', 'SSR']),
      spec('python', 'Python', ['OOP', 'Async', 'Data Structures', 'Testing', 'Packaging']),
      spec('django', 'Django', ['ORM', 'Views', 'Auth', 'REST Framework', 'Migrations']),
      spec('fastapi', 'FastAPI', ['Routing', 'Pydantic', 'Dependency Injection', 'Async', 'OpenAPI']),
      spec('flask', 'Flask', ['Routing', 'Blueprints', 'Jinja', 'Auth', 'Extensions']),
      spec('java', 'Java', ['OOP', 'Collections', 'Concurrency', 'JVM', 'Streams']),
      spec('spring_boot', 'Spring Boot', ['DI', 'Spring MVC', 'JPA', 'Security', 'Actuator']),
      spec('cpp', 'C++', ['Memory', 'STL', 'OOP', 'Concurrency', 'Templates']),
      spec('clang', 'C', ['Pointers', 'Memory', 'Arrays', 'Structs', 'Compilation']),
      spec('csharp', 'C#', ['OOP', 'LINQ', 'Async', 'Generics', 'Memory']),
      spec('dotnet', '.NET', ['ASP.NET', 'EF Core', 'DI', 'Middleware', 'Hosting']),
      spec('golang', 'Go', ['Goroutines', 'Channels', 'Interfaces', 'Packages', 'Testing']),
      spec('rust', 'Rust', ['Ownership', 'Borrowing', 'Traits', 'Error Handling', 'Concurrency']),
      spec('php', 'PHP', ['OOP', 'Composer', 'Sessions', 'Security', 'Performance']),
      spec('laravel', 'Laravel', ['Eloquent', 'Routing', 'Auth', 'Queues', 'Blade']),
      spec('kotlin', 'Kotlin', ['Coroutines', 'Null Safety', 'Collections', 'Android Basics', 'Multiplatform']),
      spec('ruby', 'Ruby', ['OOP', 'Rails Basics', 'Gems', 'Metaprogramming', 'Testing']),
      spec('swift', 'Swift', ['Optionals', 'Protocols', 'Concurrency', 'UIKit/SwiftUI', 'Memory']),
      spec('react', 'React.js', ['Hooks', 'State', 'Effects', 'Performance', 'Testing']),
      spec('angular', 'Angular', ['Components', 'RxJS', 'Dependency Injection', 'Routing', 'Forms']),
      spec('vue', 'Vue', ['Composition API', 'Reactivity', 'Vue Router', 'Pinia', 'SSR']),
      spec('svelte', 'Svelte', ['Reactivity', 'Stores', 'Components', 'Transitions', 'SvelteKit']),
      spec('html_css', 'HTML & CSS', ['Semantics', 'Flexbox', 'Grid', 'Accessibility', 'Responsive']),
      spec('tailwind', 'Tailwind CSS', ['Utility Classes', 'Responsive', 'Custom Theme', 'Layout', 'Dark Mode']),
      spec('nestjs', 'NestJS', ['Modules', 'DI', 'Controllers', 'Guards', 'Pipes']),
      spec('mern', 'MERN Stack', ['React', 'Node.js', 'Express', 'MongoDB', 'Auth']),
      spec('mysql', 'MySQL', ['SQL Queries', 'Indexes', 'Joins', 'Transactions', 'Normalization']),
      spec('postgresql', 'PostgreSQL', ['SQL Queries', 'Indexes', 'Joins', 'Transactions', 'JSON/JSONB']),
      spec('sqlserver', 'SQL Server', ['T-SQL', 'Indexes', 'Stored Procedures', 'Transactions', 'Security']),
      spec('oracle_db', 'Oracle Database', ['SQL', 'PL/SQL', 'Indexes', 'Transactions', 'Performance']),
      spec('sqlite', 'SQLite', ['SQL Queries', 'Schema Design', 'Indexes', 'Transactions', 'Embedded Use']),
      spec('redis', 'Redis', ['Data Structures', 'Caching', 'Pub/Sub', 'Persistence', 'Clustering']),
      spec('firebase', 'Firebase', ['Auth', 'Firestore', 'Realtime DB', 'Cloud Functions', 'Security Rules']),
      spec('dynamodb', 'DynamoDB', ['Keys', 'Indexes', 'Queries', 'Capacity', 'Streams']),
      spec('cassandra', 'Cassandra', ['Data Modeling', 'CQL', 'Partitioning', 'Consistency', 'Clusters']),
      spec('aws', 'AWS', ['EC2', 'S3', 'IAM', 'Lambda', 'Networking']),
      spec('azure', 'Azure', ['Compute', 'Storage', 'Identity', 'Functions', 'Networking']),
      spec('gcp', 'GCP', ['Compute Engine', 'Cloud Storage', 'IAM', 'Cloud Functions', 'Networking']),
      spec('selenium', 'Selenium', ['WebDriver', 'Locators', 'Waits', 'Page Object', 'CI Integration']),
      spec('cypress', 'Cypress', ['Commands', 'Assertions', 'Fixtures', 'Interception', 'CI']),
      spec('playwright', 'Playwright', ['Locators', 'Assertions', 'Tracing', 'Parallel', 'CI']),
      spec('jest', 'Jest', ['Matchers', 'Mocks', 'Async Tests', 'Coverage', 'Snapshots']),
      spec('unity', 'Unity', ['Scenes', 'GameObjects', 'Scripting', 'Physics', 'UI']),
      spec('unreal', 'Unreal Engine', ['Blueprints', 'Actors', 'C++ Basics', 'Physics', 'UI']),
      spec('ethical_hacking', 'Ethical Hacking', [
        'Reconnaissance',
        'Exploitation',
        'Privilege Escalation',
        'Reporting',
        'Tools',
      ]),
      spec('secure_coding', 'Secure Coding', [
        'Input Validation',
        'Auth Flaws',
        'Crypto Basics',
        'Least Privilege',
        'Code Review',
      ]),
      spec('owasp', 'OWASP', [
        'Injection',
        'Broken Auth',
        'XSS',
        'SSRF',
        'Security Misconfiguration',
      ]),
      spec('web_security', 'Web Security', [
        'HTTPS/TLS',
        'CORS',
        'CSRF',
        'Session Security',
        'Headers',
      ]),
      spec('oop', 'Object-Oriented Programming', [
        'Encapsulation',
        'Inheritance',
        'Polymorphism',
        'Abstraction',
        'SOLID',
      ]),
      spec('dbms', 'Database Management Systems', [
        'ER Modeling',
        'Normalization',
        'Transactions',
        'Indexing',
        'Concurrency Control',
      ]),
      spec('operating_systems', 'Operating Systems', [
        'Processes',
        'Threads',
        'Memory Management',
        'Scheduling',
        'File Systems',
      ]),
      spec('computer_networks', 'Computer Networks', [
        'OSI/TCP-IP',
        'Routing',
        'DNS',
        'HTTP',
        'Congestion Control',
      ]),
      spec('software_engineering_fundamentals', 'Software Engineering Fundamentals', [
        'SDLC',
        'Requirements',
        'Design Patterns',
        'Testing',
        'Maintenance',
      ]),
      spec('prompt_engineering', 'Prompt Engineering', [
        'Prompt Design',
        'Few-Shot',
        'Chain of Thought',
        'Evaluation',
        'Safety',
      ]),
      spec('ai_agents', 'AI Agents', [
        'Tool Use',
        'Planning',
        'Memory',
        'Multi-Agent',
        'Evaluation',
      ]),
      spec('rag', 'RAG', [
        'Chunking',
        'Embeddings',
        'Retrieval',
        'Reranking',
        'Grounding',
      ]),
      spec('mobile', 'Mobile Development', ['Mobile UI', 'APIs', 'State', 'Offline', 'Release']),
      spec('qa', 'QA Engineering', ['Test Design', 'Bug Reporting', 'Regression', 'API Testing', 'Coverage']),
      spec('sqa_automation', 'SQA Automation', ['Selenium', 'Cypress', 'CI Pipelines', 'Assertions', 'Flaky Tests']),
      spec('game_dev', 'Game Development', ['Game Loops', 'Physics', 'Rendering', 'Networking', 'Optimization']),
      spec('dsa', 'Data Structures & Algorithms', [
        'Arrays',
        'Strings',
        'Linked Lists',
        'Stacks',
        'Queues',
        'Trees',
        'BST',
        'Heaps',
        'Graphs',
        'Dynamic Programming',
        'Greedy',
        'Backtracking',
      ]),
      spec('system_design_topics', 'System Design Topics', [
        'Scalability',
        'Caching',
        'Load Balancers',
        'Databases',
        'Sharding',
        'Message Queues',
        'Microservices',
        'CAP Theorem',
        'High-Level Design',
        'Low-Level Design',
      ]),
      spec('graphql', 'GraphQL', ['Schema', 'Resolvers', 'N+1', 'Subscriptions', 'Federation']),
      spec('kafka', 'Apache Kafka', ['Topics', 'Partitions', 'Consumers', 'Exactly-Once', 'Streams']),
      spec('elasticsearch', 'Elasticsearch', ['Indexing', 'Queries', 'Aggregations', 'Mappings', 'Scaling']),
      spec('rabbitmq', 'RabbitMQ', ['Queues', 'Exchanges', 'Ack/Nack', 'Dead Letters', 'Patterns']),
      spec('grpc', 'gRPC', ['Protobuf', 'Unary/Streaming', 'Deadlines', 'Interceptors', 'Load Balancing']),
      spec('websocket', 'WebSockets', ['Handshake', 'Frames', 'Scaling', 'Auth', 'Heartbeats']),
      spec('microservices', 'Microservices', [
        'Service Boundaries',
        'API Gateway',
        'Service Mesh',
        'Saga',
        'Observability',
      ]),
      spec('system_design', 'System Design', [
        'Requirements',
        'Capacity Estimation',
        'API Design',
        'Data Models',
        'Trade-offs',
      ]),
      spec('lld', 'Low-Level Design', [
        'SOLID',
        'Design Patterns',
        'Class Diagrams',
        'Extensibility',
        'Testing Hooks',
      ]),
      spec('blockchain', 'Blockchain', [
        'Consensus',
        'Smart Contracts',
        'Wallets',
        'Gas/Fees',
        'Security Risks',
      ]),
      spec('scala', 'Scala', ['FP', 'Collections', 'Implicits', 'Akka Basics', 'Spark Integration']),
      spec('elixir', 'Elixir', ['OTP', 'Processes', 'Phoenix', 'Fault Tolerance', 'Concurrency']),
    ],
  },
  {
    key: 'information_technology',
    label: 'Information Technology',
    specializations: [
      spec('it_support', 'IT Support', [
        'Troubleshooting',
        'Networking',
        'Active Directory',
        'Ticketing',
        'Hardware',
        'Remote Support',
      ]),
      spec('systems_admin', 'Systems Administration', [
        'Linux',
        'Windows Server',
        'Virtualization',
        'Backups',
        'Patching',
        'Scripting',
      ]),
      spec('it_security', 'IT Security', [
        'Access Control',
        'Incident Response',
        'SIEM',
        'Endpoint Security',
        'Compliance Basics',
      ]),
      spec('cloud_admin', 'Cloud Administration', [
        'IAM',
        'Compute',
        'Storage',
        'Networking',
        'Cost Management',
      ]),
      spec('helpdesk', 'Help Desk', [
        'SLA',
        'Customer Communication',
        'Escalation',
        'Knowledge Base',
        'Asset Tracking',
      ]),
      spec('virtualization', 'Virtualization', [
        'Hypervisors',
        'VMware/Hyper-V',
        'Containers vs VMs',
        'Snapshots',
        'Resource Pools',
      ]),
      spec('ethical_hacking', 'Ethical Hacking', [
        'Reconnaissance',
        'Exploitation',
        'Privilege Escalation',
        'Reporting',
        'Tools',
      ]),
      spec('secure_coding', 'Secure Coding', [
        'Input Validation',
        'Auth Flaws',
        'Crypto Basics',
        'Least Privilege',
        'Code Review',
      ]),
      spec('owasp', 'OWASP', [
        'Injection',
        'Broken Auth',
        'XSS',
        'SSRF',
        'Security Misconfiguration',
      ]),
      spec('web_security', 'Web Security', [
        'HTTPS/TLS',
        'CORS',
        'CSRF',
        'Session Security',
        'Headers',
      ]),
    ],
  },
  {
    key: 'data_science',
    label: 'Data Science',
    specializations: [
      spec('analytics', 'Analytics', [
        'SQL',
        'Dashboards',
        'A/B Testing',
        'Metrics',
        'Storytelling',
      ]),
      spec('machine_learning', 'Machine Learning', [
        'Supervised Learning',
        'Unsupervised Learning',
        'Feature Engineering',
        'Model Evaluation',
        'Hyperparameter Tuning',
      ]),
      spec('data_engineering', 'Data Engineering', [
        'ETL/ELT',
        'Pipelines',
        'Warehousing',
        'Spark',
        'Airflow',
        'Data Quality',
      ]),
      spec('statistics', 'Statistics', [
        'Probability',
        'Hypothesis Testing',
        'Regression',
        'Sampling',
        'Bayesian Basics',
      ]),
      spec('business_intelligence', 'Business Intelligence', [
        'Dimensional Modeling',
        'Tableau/Power BI',
        'KPI Design',
        'Self-Serve Analytics',
      ]),
      spec('mlops', 'MLOps', [
        'Model Registry',
        'Feature Stores',
        'Monitoring Drift',
        'CI/CD for ML',
        'Serving',
      ]),
      spec('computer_vision_ds', 'Computer Vision', [
        'Image Classification',
        'Detection',
        'Segmentation',
        'Augmentation',
        'Evaluation Metrics',
      ]),
      spec('time_series', 'Time Series', [
        'Forecasting',
        'Stationarity',
        'ARIMA/Prophet',
        'Feature Lags',
        'Anomaly Detection',
      ]),
    ],
  },
  {
    key: 'artificial_intelligence',
    label: 'Artificial Intelligence',
    specializations: [
      spec('machine_learning', 'Machine Learning', [
        'Regression',
        'Classification',
        'Ensembles',
        'Validation',
        'Bias/Variance',
      ]),
      spec('deep_learning', 'Deep Learning', [
        'Neural Networks',
        'CNNs',
        'RNNs',
        'Transformers',
        'Optimization',
      ]),
      spec('nlp', 'NLP', [
        'Tokenization',
        'Embeddings',
        'LLMs',
        'Text Classification',
        'Seq2Seq',
      ]),
      spec('computer_vision', 'Computer Vision', [
        'CNNs',
        'Object Detection',
        'Segmentation',
        'Transfer Learning',
        'Vision Transformers',
      ]),
      spec('reinforcement_learning', 'Reinforcement Learning', [
        'MDPs',
        'Q-Learning',
        'Policy Gradients',
        'Reward Design',
        'Exploration',
      ]),
      spec('generative_ai', 'Generative AI', [
        'Diffusion',
        'GANs',
        'LLM Fine-Tuning',
        'Evaluation',
        'Safety',
      ]),
      spec('prompt_engineering', 'Prompt Engineering', [
        'Prompt Design',
        'Few-Shot',
        'Chain of Thought',
        'Evaluation',
        'Safety',
      ]),
      spec('ai_agents', 'AI Agents', [
        'Tool Use',
        'Planning',
        'Memory',
        'Multi-Agent',
        'Evaluation',
      ]),
      spec('rag', 'RAG', [
        'Chunking',
        'Embeddings',
        'Retrieval',
        'Reranking',
        'Grounding',
      ]),
      spec('speech_ai', 'Speech AI', [
        'ASR',
        'TTS',
        'Speaker ID',
        'Noise Robustness',
        'Latency',
      ]),
    ],
  },
]

export const INTERVIEW_CATALOG_DEPARTMENTS: DepartmentConfig[] = [
  buildComputerScienceDepartmentFromLegacy(),
  ...OTHER_DEPARTMENTS,
  ...COMPUTER_FIELD_DEPARTMENTS,
]
