/**
 * Pakistan Top 30 computer-tech employers — learning path packs.
 * Computer / software tech only (no banks or telecom carriers).
 */

export type PakistanCompanyArchetype = 'services' | 'product' | 'studio' | 'deep_tech'

export type PakistanCompanyPack = {
  slug: string
  title: string
  archetype: PakistanCompanyArchetype
  cities: string
  stacks: string[]
  departmentKey: string
  specializationKeys: string[]
  technicalTopics: string[]
  codingCategories: string[]
  systemDesignTopics: string[]
  /** Prefer true system_design interview type when archetype needs SD depth */
  useSystemDesignType: boolean
  behavioralCompetencies: string[]
  hrSectionLabels: string[]
  /** Technical share of mixed mock (0–100); rest split soft skills */
  mockTechRatio: number
  mockUnlock: number
  difficultyLabel: 'Beginner' | 'Intermediate' | 'Advanced'
  cultureNotes: string
}

const HR_DEFAULT = [
  'Introduction',
  'Motivation',
  'Background',
  'Availability',
  'Salary',
  'Work Preferences',
]

const BEH_SERVICES = [
  'Communication',
  'Teamwork',
  'Accountability',
  'Time Management',
  'Customer Focus',
  'Adaptability',
]

const BEH_PRODUCT = [
  'Ownership',
  'Problem Solving',
  'Communication',
  'Initiative',
  'Decision Making',
  'Collaboration',
]

const BEH_STUDIO = [
  'Ownership',
  'Learning Mindset',
  'Communication',
  'Conflict Resolution',
  'Leadership',
  'Accountability',
]

const BEH_DEEP = [
  'Ownership',
  'Problem Solving',
  'Learning Mindset',
  'Accountability',
  'Decision Making',
  'Communication',
]

const CODING_SERVICES = ['Arrays', 'Strings', 'Hashing', 'Sorting', 'Two Pointers', 'Stacks']
const CODING_PRODUCT = [
  'Arrays',
  'Hashing',
  'Trees',
  'Graphs',
  'Sliding Window',
  'Dynamic Programming',
]
const CODING_STUDIO = [
  'Arrays',
  'Hashing',
  'Trees',
  'Graphs',
  'Binary Search',
  'Dynamic Programming',
]
const CODING_DEEP = [
  'Arrays',
  'Trees',
  'Graphs',
  'Dynamic Programming',
  'Heap / Priority Queue',
  'Backtracking',
]

const SD_LIGHT = ['API Design', 'Caching', 'Databases', 'Scalability']
const SD_PRODUCT = [
  'Scalability',
  'Caching',
  'Load Balancing',
  'API Design',
  'Message Queues',
  'Microservices',
  'Databases',
]
const SD_DEEP = [
  'Distributed Systems',
  'Scalability',
  'Consistency',
  'Caching',
  'Microservices',
  'Monitoring',
  'CAP Theorem',
]

function pack(
  partial: Omit<PakistanCompanyPack, 'hrSectionLabels'> & { hrSectionLabels?: string[] },
): PakistanCompanyPack {
  return {
    hrSectionLabels: partial.hrSectionLabels ?? HR_DEFAULT,
    ...partial,
  }
}

/** Canonical Top 30 computer-tech companies in Pakistan. */
export const PAKISTAN_TECH_TOP_30: PakistanCompanyPack[] = [
  // —— Services (10) ——
  pack({
    slug: 'systems-limited',
    title: 'Systems Limited',
    archetype: 'services',
    cities: 'Lahore',
    stacks: ['.NET', 'Java', 'JavaScript', 'SQL'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Auth', 'Deployment', 'System Design'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 65,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Enterprise delivery, client demos, and multi-stack full-stack rounds.',
  }),
  pack({
    slug: 'netsol',
    title: 'NetSol',
    archetype: 'services',
    cities: 'Lahore',
    stacks: ['.NET', 'Java', 'SQL', 'Cloud'],
    departmentKey: 'software_engineering',
    specializationKeys: ['backend'],
    technicalTopics: ['APIs', 'Databases', 'Microservices', 'Caching', 'Auth'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 70,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Financing/leasing domain software; expect SQL depth and delivery ownership.',
  }),
  pack({
    slug: 'contour-software',
    title: 'Contour Software',
    archetype: 'services',
    cities: 'Lahore / Karachi',
    stacks: ['.NET', 'SQL', 'Web'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Auth', 'Deployment', 'CSS'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 65,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Product-engineering hybrid; clean coding and stakeholder communication.',
  }),
  pack({
    slug: 'techlogix',
    title: 'Techlogix',
    archetype: 'services',
    cities: 'Lahore / Islamabad',
    stacks: ['Java', 'Integration', 'Enterprise'],
    departmentKey: 'software_engineering',
    specializationKeys: ['backend'],
    technicalTopics: ['APIs', 'Databases', 'Microservices', 'Auth', 'System Design'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 70,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Enterprise integrations and reliable backend delivery.',
  }),
  pack({
    slug: '10pearls',
    title: '10Pearls',
    archetype: 'services',
    cities: 'Karachi / Lahore / Islamabad',
    stacks: ['JavaScript', 'React', 'Node', 'Cloud'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['React', 'APIs', 'Databases', 'Auth', 'Deployment'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 65,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'US-client delivery; expect overlap hours and clear communication.',
  }),
  pack({
    slug: 'folio3',
    title: 'Folio3',
    archetype: 'services',
    cities: 'Karachi / Lahore',
    stacks: ['JavaScript', 'Mobile', 'Cloud'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'React', 'Databases', 'Auth', 'Deployment'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 65,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Product and services mix; full-stack and mobile-friendly rounds.',
  }),
  pack({
    slug: 'devsinc',
    title: 'Devsinc',
    archetype: 'services',
    cities: 'Lahore / Islamabad',
    stacks: ['JavaScript', 'Python', 'React'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'React', 'Databases', 'Auth', 'Deployment'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 65,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Fast-growth services culture; fundamentals plus delivery stories.',
  }),
  pack({
    slug: 'nextbridge',
    title: 'Nextbridge',
    archetype: 'services',
    cities: 'Lahore',
    stacks: ['.NET', 'Web', 'SQL'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Auth', 'Deployment', 'System Design'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 65,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Long-running product teams; expect practical coding and SQL.',
  }),
  pack({
    slug: 'gaditek',
    title: 'Gaditek',
    archetype: 'services',
    cities: 'Karachi',
    stacks: ['PHP', 'JavaScript', 'Cloud', 'SaaS'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Auth', 'Caching', 'Deployment'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 65,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'SaaS product engineering inside a services group.',
  }),
  pack({
    slug: 'ovex',
    title: 'Ovex Technologies',
    archetype: 'services',
    cities: 'Lahore / Islamabad',
    stacks: ['JavaScript', 'Mobile', 'Web'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'React', 'Databases', 'Auth', 'Deployment'],
    codingCategories: CODING_SERVICES,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: false,
    behavioralCompetencies: BEH_SERVICES,
    mockTechRatio: 65,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Client projects across web/mobile; clear communication matters.',
  }),

  // —— Product (10) ——
  pack({
    slug: 'careem',
    title: 'Careem',
    archetype: 'product',
    cities: 'Karachi / Lahore / Islamabad',
    stacks: ['Backend', 'Mobile', 'Geo', 'Payments'],
    departmentKey: 'software_engineering',
    specializationKeys: ['backend'],
    technicalTopics: ['APIs', 'Microservices', 'Databases', 'Caching', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Marketplace scale, reliability, and ownership of user impact.',
  }),
  pack({
    slug: 'motive',
    title: 'Motive',
    archetype: 'product',
    cities: 'Islamabad / Lahore',
    stacks: ['Backend', 'Data', 'IoT', 'Mobile'],
    departmentKey: 'software_engineering',
    specializationKeys: ['backend'],
    technicalTopics: ['APIs', 'Microservices', 'Databases', 'Caching', 'System Design'],
    codingCategories: CODING_DEEP,
    systemDesignTopics: SD_DEEP,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_DEEP,
    mockTechRatio: 85,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'High engineering bar; production debugging and distributed systems.',
  }),
  pack({
    slug: 'dubizzle-labs',
    title: 'Dubizzle Labs',
    archetype: 'product',
    cities: 'Lahore / Karachi',
    stacks: ['Marketplace', 'Backend', 'Search'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Caching', 'React', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Classifieds/marketplace scale and search relevance.',
  }),
  pack({
    slug: 'bazaar-technologies',
    title: 'Bazaar Technologies',
    archetype: 'product',
    cities: 'Karachi / Lahore',
    stacks: ['Marketplace', 'Logistics', 'Mobile'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Caching', 'Microservices', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'B2B commerce and logistics; product sense plus reliability.',
  }),
  pack({
    slug: 'tajir',
    title: 'Tajir',
    archetype: 'product',
    cities: 'Lahore / Karachi',
    stacks: ['Mobile', 'Backend', 'Retail'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Auth', 'React', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 75,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Retail digitization; mobile-first product thinking.',
  }),
  pack({
    slug: 'postex',
    title: 'PostEx',
    archetype: 'product',
    cities: 'Lahore / Karachi',
    stacks: ['Logistics', 'APIs', 'Backend'],
    departmentKey: 'software_engineering',
    specializationKeys: ['backend'],
    technicalTopics: ['APIs', 'Databases', 'Caching', 'Microservices', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Courier/logistics platforms; tracking and throughput design.',
  }),
  pack({
    slug: 'creditbook',
    title: 'CreditBook',
    archetype: 'product',
    cities: 'Karachi / Lahore',
    stacks: ['Fintech', 'Mobile', 'Backend'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Auth', 'Caching', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 75,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'SMB fintech; trust, data integrity, and simple UX.',
  }),
  pack({
    slug: 'retailo',
    title: 'Retailo',
    archetype: 'product',
    cities: 'Karachi / Lahore',
    stacks: ['B2B Commerce', 'Logistics', 'Mobile'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Caching', 'React', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'B2B retail ops; inventory, orders, and fulfillment systems.',
  }),
  pack({
    slug: 'dastgyr',
    title: 'Dastgyr',
    archetype: 'product',
    cities: 'Karachi / Lahore',
    stacks: ['B2B Marketplace', 'Backend', 'Mobile'],
    departmentKey: 'software_engineering',
    specializationKeys: ['backend'],
    technicalTopics: ['APIs', 'Databases', 'Caching', 'Microservices', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Wholesale marketplace; catalog, pricing, and logistics APIs.',
  }),
  pack({
    slug: 'bykea',
    title: 'Bykea',
    archetype: 'product',
    cities: 'Karachi / Lahore',
    stacks: ['Mobility', 'Mobile', 'Backend'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Caching', 'Auth', 'System Design'],
    codingCategories: CODING_PRODUCT,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_PRODUCT,
    mockTechRatio: 75,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'On-demand mobility/delivery; realtime matching and reliability.',
  }),

  // —— Studio / high-signal brands (6) ——
  pack({
    slug: 'arbisoft',
    title: 'Arbisoft',
    archetype: 'studio',
    cities: 'Lahore',
    stacks: ['Python', 'JavaScript', 'EdTech', 'Data'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'React', 'System Design', 'Caching'],
    codingCategories: CODING_STUDIO,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_STUDIO,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Strong CS fundamentals culture; expect thoughtful coding rounds.',
  }),
  pack({
    slug: 'confiz',
    title: 'Confiz',
    archetype: 'studio',
    cities: 'Lahore',
    stacks: ['.NET', 'Cloud', 'Enterprise'],
    departmentKey: 'software_engineering',
    specializationKeys: ['backend'],
    technicalTopics: ['APIs', 'Databases', 'Microservices', 'Caching', 'System Design'],
    codingCategories: CODING_STUDIO,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_STUDIO,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Enterprise product engineering with solid design discussions.',
  }),
  pack({
    slug: 'venturedive',
    title: 'VentureDive',
    archetype: 'studio',
    cities: 'Karachi / Lahore',
    stacks: ['Mobile', 'Backend', 'Product'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'React', 'Databases', 'Auth', 'System Design'],
    codingCategories: CODING_STUDIO,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_STUDIO,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Product studio craft; polish, ownership, and system thinking.',
  }),
  pack({
    slug: 'tkxel',
    title: 'Tkxel',
    archetype: 'studio',
    cities: 'Lahore / Karachi',
    stacks: ['JavaScript', 'Cloud', 'AI-ready'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'React', 'Databases', 'Deployment', 'System Design'],
    codingCategories: CODING_STUDIO,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_STUDIO,
    mockTechRatio: 75,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Digital product delivery with modern web stacks.',
  }),
  pack({
    slug: 'emumba',
    title: 'Emumba',
    archetype: 'studio',
    cities: 'Islamabad',
    stacks: ['JavaScript', 'React', 'Cloud'],
    departmentKey: 'software_engineering',
    specializationKeys: ['frontend'],
    technicalTopics: ['React', 'TypeScript', 'Performance', 'APIs', 'Accessibility'],
    codingCategories: CODING_STUDIO,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_STUDIO,
    mockTechRatio: 75,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Frontend/product engineering strength; UI quality and APIs.',
  }),
  pack({
    slug: 'tintash',
    title: 'Tintash',
    archetype: 'studio',
    cities: 'Lahore / Islamabad',
    stacks: ['Mobile', 'Games', 'Product'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'React', 'Databases', 'Auth', 'Performance'],
    codingCategories: CODING_STUDIO,
    systemDesignTopics: SD_LIGHT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_STUDIO,
    mockTechRatio: 75,
    mockUnlock: 70,
    difficultyLabel: 'Intermediate',
    cultureNotes: 'Product and mobile craft; expect practical coding and design trade-offs.',
  }),

  // —— Deep-tech / platforms (4) ——
  pack({
    slug: 'afiniti',
    title: 'Afiniti',
    archetype: 'deep_tech',
    cities: 'Islamabad / Lahore',
    stacks: ['AI', 'Data', 'Backend'],
    departmentKey: 'artificial_intelligence',
    specializationKeys: ['machine_learning'],
    technicalTopics: ['Machine Learning', 'APIs', 'Databases', 'System Design', 'Caching'],
    codingCategories: CODING_DEEP,
    systemDesignTopics: SD_DEEP,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_DEEP,
    mockTechRatio: 85,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'AI/pairing optimization; strong algorithms and systems thinking.',
  }),
  pack({
    slug: 'curemd',
    title: 'CureMD',
    archetype: 'deep_tech',
    cities: 'Lahore',
    stacks: ['HealthTech', '.NET', 'Cloud'],
    departmentKey: 'software_engineering',
    specializationKeys: ['full_stack'],
    technicalTopics: ['APIs', 'Databases', 'Auth', 'System Design', 'Caching'],
    codingCategories: CODING_STUDIO,
    systemDesignTopics: SD_PRODUCT,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_DEEP,
    mockTechRatio: 80,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Healthcare SaaS; correctness, compliance-minded design, reliability.',
  }),
  pack({
    slug: 'i2c',
    title: 'i2c',
    archetype: 'deep_tech',
    cities: 'Lahore',
    stacks: ['Payments', 'Java', 'Distributed'],
    departmentKey: 'software_engineering',
    specializationKeys: ['backend'],
    technicalTopics: ['APIs', 'Databases', 'Caching', 'Microservices', 'System Design'],
    codingCategories: CODING_DEEP,
    systemDesignTopics: SD_DEEP,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_DEEP,
    mockTechRatio: 85,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Payments platform scale; consistency, latency, and security awareness.',
  }),
  pack({
    slug: 'sp-global-pakistan',
    title: 'S&P Global Pakistan',
    archetype: 'deep_tech',
    cities: 'Islamabad / Lahore',
    stacks: ['Data', 'Backend', 'Cloud'],
    departmentKey: 'data_science',
    specializationKeys: ['data_engineering'],
    technicalTopics: ['Databases', 'APIs', 'Caching', 'System Design', 'Monitoring'],
    codingCategories: CODING_DEEP,
    systemDesignTopics: SD_DEEP,
    useSystemDesignType: true,
    behavioralCompetencies: BEH_DEEP,
    mockTechRatio: 85,
    mockUnlock: 75,
    difficultyLabel: 'Advanced',
    cultureNotes: 'Data platforms and financial tech; quality and analytical rigor.',
  }),
]

export const PAKISTAN_TECH_TOP_30_COUNT = PAKISTAN_TECH_TOP_30.length

export function getPakistanCompanyBySlug(slug: string): PakistanCompanyPack | undefined {
  return PAKISTAN_TECH_TOP_30.find((c) => c.slug === slug)
}
