import type { LegalPageContent } from './types'

export const TERMS_OF_USE: LegalPageContent = {
  slug: 'terms',
  eyebrow: 'Terms of Use',
  title: 'Rules for using HireQuest',
  summary:
    'These terms describe what you can expect from the platform and what we expect from you when practicing interviews and using AI features.',
  lastUpdated: 'August 17, 2026',
  chips: ['Acceptable use', 'AI disclaimer', 'Accounts', 'Billing'],
  sealVariant: 'terms',
  disclaimer:
    'These Terms of Use summarize how HireQuest is intended to be used. They are not legal advice. For binding contractual terms in your jurisdiction, consult qualified counsel.',
  sections: [
    {
      id: 'agreement',
      title: 'Agreement',
      paragraphs: [
        'By accessing or using HireQuest, you agree to these Terms of Use and our Privacy Policy. If you do not agree, do not use the service.',
        'We may update these terms by posting a revised version and updating the “Last updated” date. Continued use after changes constitutes acceptance.',
      ],
    },
    {
      id: 'eligibility',
      title: 'Eligibility',
      paragraphs: [
        'You must be old enough to form a binding contract in your jurisdiction and not prohibited from using the service under applicable law.',
        'If you use HireQuest on behalf of an organization, you represent that you have authority to bind that organization to these terms.',
      ],
    },
    {
      id: 'accounts',
      title: 'Accounts',
      bullets: [
        'Provide accurate account information and keep credentials confidential.',
        'You are responsible for activity under your account.',
        'Notify us promptly if you suspect unauthorized access.',
        'We may suspend or terminate accounts that violate these terms or pose security risk.',
      ],
    },
    {
      id: 'acceptable-use',
      title: 'Acceptable use',
      bullets: [
        'Use HireQuest for lawful interview preparation and career development.',
        'Do not attempt to reverse engineer, scrape, or overload the platform.',
        'Do not upload malware, unlawful content, or material you lack rights to share.',
        'Do not harass others, impersonate people, or misuse AI outputs to deceive employers or candidates.',
        'Do not use the service to build a competing product using unauthorized automated access.',
      ],
    },
    {
      id: 'ai-disclaimer',
      title: 'AI & output disclaimer',
      paragraphs: [
        'Interview questions, feedback, scores, and suggestions are generated by AI and may be incomplete, outdated, or incorrect. They are for practice only — not hiring decisions, legal advice, or guaranteed interview outcomes.',
        'You are responsible for reviewing AI output before relying on it. Do not submit confidential employer data or trade secrets into prompts or resumes unless you are permitted to do so.',
      ],
    },
    {
      id: 'subscriptions',
      title: 'Subscriptions & billing',
      paragraphs: [
        'Some features may be offered free; paid plans, if available, will show pricing and renewal terms at checkout. Fees are non-refundable except where required by law or explicitly stated.',
        'We may change pricing or features with reasonable notice for future billing periods.',
      ],
    },
    {
      id: 'intellectual-property',
      title: 'Intellectual property',
      paragraphs: [
        'HireQuest, its branding, software, and content are owned by us or our licensors. You receive a limited, non-exclusive license to use the service for personal or authorized organizational preparation.',
        'You retain ownership of content you submit (such as resumes and answers). You grant us a license to host, process, and display that content solely to operate and improve the service.',
      ],
    },
    {
      id: 'privacy',
      title: 'Privacy',
      paragraphs: [
        'Our Privacy Policy explains how we collect and use personal information. Using HireQuest also means you agree to that policy.',
      ],
    },
    {
      id: 'disclaimers',
      title: 'Disclaimers',
      paragraphs: [
        'THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.',
        'We do not guarantee uninterrupted access, error-free AI output, or specific career results.',
      ],
    },
    {
      id: 'limitation',
      title: 'Limitation of liability',
      paragraphs: [
        'TO THE MAXIMUM EXTENT PERMITTED BY LAW, HIREQUEST AND ITS AFFILIATES WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE.',
        'Our total liability for any claim relating to the service is limited to the amount you paid us in the twelve (12) months before the claim, or one hundred US dollars (USD $100), whichever is greater, unless applicable law requires otherwise.',
      ],
    },
    {
      id: 'termination',
      title: 'Termination',
      paragraphs: [
        'You may stop using HireQuest at any time. We may suspend or terminate access if you breach these terms, create risk, or where required by law.',
        'Sections that by nature should survive termination (such as disclaimers, limitation of liability, and intellectual property) will continue to apply.',
      ],
    },
    {
      id: 'contact',
      title: 'Contact',
      paragraphs: [
        'Questions about these terms? Email legal@hirequest.app (placeholder — replace with your operational contact before production launch).',
      ],
    },
    {
      id: 'changes',
      title: 'Changes',
      paragraphs: [
        'We may modify these Terms of Use. Material changes will be reflected on this page with an updated date. Your continued use after changes means you accept the revised terms.',
      ],
    },
  ],
}
